import { StyleSheet } from "react-native";

export const examReportsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "transparent" },
  container: { flex: 1, backgroundColor: "transparent" },
  content: { padding: 20, paddingTop: 8 },
  scrollBottomSpacer: { height: 100 },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "transparent",
  },
  pageTitle: { fontSize: 24, fontWeight: "800", color: "#0F172A" },
  pageSub: {
    fontSize: 14,
    color: "#64748B",
    lineHeight: 20,
    marginTop: 6,
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 8,
    marginTop: 8,
  },
  modeRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
    marginBottom: 8,
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#E2E8F0",
    alignItems: "center",
  },
  modeBtnActive: { backgroundColor: "#1E40AF" },
  modeBtnText: { fontWeight: "700", color: "#475569", fontSize: 14 },
  modeBtnTextActive: { color: "#FFFFFF" },
  loader: { marginVertical: 24 },
  listHint: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 10,
    fontWeight: "600",
  },
  showMoreBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
    marginBottom: 8,
    backgroundColor: "#EFF6FF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  showMoreText: {
    color: "#2563EB",
    fontWeight: "700",
    fontSize: 14,
  },
  summaryRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginVertical: 14 },
  summaryChip: {
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  summaryLabel: { fontSize: 11, fontWeight: "600", color: "#64748B" },
  summaryValue: { fontSize: 16, fontWeight: "800", color: "#1E40AF", marginTop: 2 },
  studentRow: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  studentRowTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  studentInfo: { flex: 1, minWidth: 0 },
  studentName: { fontSize: 16, fontWeight: "800", color: "#0F172A" },
  badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 8 },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeGraded: { backgroundColor: "#DCFCE7" },
  badgePending: { backgroundColor: "#F1F5F9" },
  badgeSeen: { backgroundColor: "#ECFDF5" },
  badgeUnseen: { backgroundColor: "#FFFBEB" },
  badgeText: { fontSize: 11, fontWeight: "700" },
  badgeTextGraded: { color: "#15803D" },
  badgeTextPending: { color: "#64748B" },
  badgeTextSeen: { color: "#059669" },
  badgeTextUnseen: { color: "#B45309" },
  reportLink: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#EFF6FF",
  },
  reportLinkText: { color: "#2563EB", fontWeight: "700", fontSize: 12 },
  scoreRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  scoreInput: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: "600",
  },
  saveBtn: {
    backgroundColor: "#2563EB",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
    minWidth: 72,
    alignItems: "center",
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: "#FFFFFF", fontWeight: "700" },
  search: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    marginBottom: 14,
  },
  reportRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    gap: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  reportAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  reportAvatarText: { color: "#1D4ED8", fontWeight: "800", fontSize: 18 },
  reportRowText: { flex: 1, minWidth: 0 },
  reportRowSub: { fontSize: 12, color: "#64748B", marginTop: 4 },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    marginTop: 12,
    alignItems: "center",
  },
  emptyTitle: { fontSize: 17, fontWeight: "700", color: "#475569" },
  emptySub: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 20,
  },
});
