import { StyleSheet } from "react-native";
import { FLOATING_TAB_BAR_INSET } from "../../src/constants/tabBar";

export const dashboardStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "transparent" },
  container: { flex: 1, paddingHorizontal: 16 },
  scrollContent: { paddingBottom: FLOATING_TAB_BAR_INSET },
  horizontalScrollContent: { paddingRight: 20 },
  headerGradient: {
    backgroundColor: "#1E40AF",
    paddingTop: 50,
    paddingBottom: 30,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    gap: 16,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#1E40AF", fontSize: 24, fontWeight: "700" },
  headerText: { flex: 1 },
  welcome: { color: "#E0E7FF", fontSize: 14, fontWeight: "500" },
  name: { fontSize: 26, fontWeight: "700", marginTop: 4, color: "#FFFFFF" },
  headerSubtitle: {
    color: "#BFDBFE",
    fontSize: 13,
    marginTop: 4,
  },
  section: { marginTop: 24 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: "#1F2937" },
  viewAllButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  viewAllText: {
    color: "#1D4ED8",
    fontWeight: "600",
    fontSize: 13,
    letterSpacing: 0.2,
    marginRight: 2,
  },
  slideCard: {
    width: 260,
    height: 142,
    padding: 14,
    borderRadius: 16,
    marginRight: 12,
    marginBottom: 8,
    backgroundColor: "#FFFFFF",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  slideCardTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  slideCardTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  slideCardSubtitle: {
    fontSize: 13,
    color: "#2563EB",
    fontWeight: "600",
    marginBottom: 2,
  },
  slideCardText: { color: "#6B7280", fontSize: 13, lineHeight: 18 },
  slideCardAction: { color: "#2563EB", fontWeight: "700", fontSize: 12 },
  messageCardAccent: { borderLeftWidth: 4, borderLeftColor: "#2563EB" },
  messageIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#EFF6FF",
    justifyContent: "center",
    alignItems: "center",
  },
  examCardAccent: {
    backgroundColor: "#F9FAFB",
    borderLeftWidth: 4,
    borderLeftColor: "#7C3AED",
  },
  hwHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  daysLeft: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: "700",
  },
  scheduleSlideCard: {
    backgroundColor: "#1F2937",
    height: 118,
    justifyContent: "center",
    gap: 10,
    borderLeftWidth: 4,
    borderLeftColor: "#38BDF8",
  },
  scheduleSlideCardCurrent: {
    backgroundColor: "#064E3B",
    height: 128,
    borderLeftWidth: 4,
    borderLeftColor: "#34D399",
    borderWidth: 2,
    borderColor: "#34D399",
    shadowColor: "#34D399",
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 4,
  },
  scheduleNowBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#34D399",
    color: "#064E3B",
    fontSize: 11,
    fontWeight: "800",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 4,
    overflow: "hidden",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  scheduleDateTime: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  scheduleDateTimeCurrent: { color: "#A7F3D0" },
  scheduleSubject: {
    color: "#F8FAFC",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  scheduleSubjectCurrent: { color: "#ECFDF5" },
  scheduleNoClassesCard: {
    backgroundColor: "#F1F5F9",
    height: 118,
    justifyContent: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#CBD5E1",
  },
  scheduleNoClassesTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 8,
  },
  scheduleNoClassesText: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  hwNoWorkCard: {
    backgroundColor: "#F8FAFC",
    height: 142,
    justifyContent: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#CBD5E1",
  },
  examNoWorkCard: {
    backgroundColor: "#FAF5FF",
    height: 142,
    justifyContent: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#C4B5FD",
  },
  hwNoWorkTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 8,
  },
  hwNoWorkText: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  feedBadge: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6B7280",
    textTransform: "uppercase",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  attendanceStatus: { fontSize: 14, fontWeight: "700", marginBottom: 2 },
  slideCardActionUrgent: { color: "#DC2626", fontWeight: "700" },
  alertButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  notificationBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: "#1E40AF",
  },
  notificationBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  logoutText: {
    color: "#1E40AF",
    fontWeight: "700",
    fontSize: 13,
  },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    padding: 24,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: { color: "#9CA3AF", fontWeight: "600", fontSize: 14 },
  absenceCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
  },
  absenceInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 14,
    minHeight: 88,
    marginBottom: 12,
    fontSize: 15,
  },
  absenceButton: {
    backgroundColor: "#2563EB",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  absenceButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 15 },
  scrollBottomSpacer: { height: 120 },
});
