import { Platform, StyleSheet, type ViewStyle } from "react-native";
import { FLOATING_TAB_BAR_INSET } from "../../src/constants/tabBar";
import {
  platformShadow,
  platformShadowAccent,
} from "../../src/utils/platformShadow";

const isWeb = Platform.OS === "web";

export const dashboardStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "transparent" },
  container: { flex: 1, paddingHorizontal: isWeb ? 0 : 16 },
  scrollContent: {
    paddingBottom: isWeb ? 32 : FLOATING_TAB_BAR_INSET,
    ...(isWeb ? { paddingTop: 0 } : null),
  },
  horizontalScrollContent: { paddingRight: 20, alignItems: "stretch" },
  /** Fixed-width cards inside horizontal carousel (web + native). */
  slideCardInCarousel: {
    width: 260,
    marginRight: 12,
    flexShrink: 0,
  },
  headerGradient: {
    backgroundColor: "#1E3A8A",
    paddingTop: isWeb ? 0 : 50,
    paddingBottom: isWeb ? 14 : 30,
    borderBottomLeftRadius: isWeb ? 0 : 28,
    borderBottomRightRadius: isWeb ? 0 : 28,
    ...platformShadow("md"),
    ...(isWeb ? { borderBottomWidth: 1, borderBottomColor: "#1E3A8A" } : null),
  },
  headerSafe: {
    backgroundColor: "#1E3A8A",
  },
  headerInnerWrap: {
    width: "100%",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: isWeb ? 0 : 16,
    gap: isWeb ? 12 : 16,
    width: "100%",
    minHeight: isWeb ? 48 : undefined,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#1E3A8A", fontSize: 24, fontWeight: "700" },
  headerText: { flex: 1, minWidth: 0 },
  welcome: { color: "#BFDBFE", fontSize: 13, fontWeight: "500" },
  name: {
    fontSize: isWeb ? 20 : 26,
    fontWeight: "800",
    marginTop: 2,
    color: "#FFFFFF",
    letterSpacing: isWeb ? 0.2 : 0,
  },
  headerSubtitle: {
    color: "#BFDBFE",
    fontSize: 13,
    marginTop: 4,
  },
  section: {
    marginTop: isWeb ? 12 : 24,
    ...(isWeb
      ? {
          backgroundColor: "#FFFFFF",
          borderRadius: 12,
          borderWidth: 1,
          borderColor: "#E2E8F0",
          padding: 20,
          ...platformShadow("sm"),
        }
      : null),
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    gap: 12,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  sectionIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sectionTitle: {
    fontSize: isWeb ? 15 : 18,
    fontWeight: "700",
    color: "#0F172A",
    flexShrink: 1,
  },
  viewAllButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: isWeb ? 8 : 12,
    paddingVertical: isWeb ? 4 : 7,
    borderRadius: 20,
    backgroundColor: isWeb ? "transparent" : "#EFF6FF",
    borderWidth: isWeb ? 0 : 1,
    borderColor: "#BFDBFE",
    flexShrink: 0,
  },
  viewAllText: {
    color: "#1D4ED8",
    fontWeight: "600",
    fontSize: 13,
    letterSpacing: 0.2,
    marginRight: 2,
  },
  slideCard: {
    width: isWeb ? undefined : 260,
    height: isWeb ? undefined : 142,
    minHeight: isWeb ? 140 : undefined,
    padding: isWeb ? 16 : 14,
    borderRadius: isWeb ? 10 : 16,
    marginRight: isWeb ? 0 : 12,
    marginBottom: isWeb ? 0 : 8,
    backgroundColor: "#FFFFFF",
    justifyContent: "space-between",
    ...(isWeb ? { borderWidth: 1, borderColor: "#E2E8F0" } : platformShadow("sm")),
  },
  slideCardTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  slideCardTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  slideCardSubtitle: {
    fontSize: 13,
    color: "#2563EB",
    fontWeight: "600",
    marginBottom: 2,
  },
  slideCardText: { color: "#6B7280", fontSize: 13, lineHeight: 18 },
  slideCardAction: { color: "#2563EB", fontWeight: "700", fontSize: 12 },
  messageCardAccent: { borderLeftWidth: 4, borderLeftColor: "#2563EB" },
  messageCardDirect: { borderLeftColor: "#7C3AED" },
  messageSenderLine: {
    fontSize: 12,
    fontWeight: "600",
    color: "#7C3AED",
    marginBottom: 4,
  },
  messagePersonalBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#EDE9FE",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 6,
  },
  messagePersonalBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6D28D9",
  },
  messageIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#EFF6FF",
    justifyContent: "center",
    alignItems: "center",
  },
  examCardAccent: {
    backgroundColor: "#F9FAFB",
    borderLeftWidth: 4,
    borderLeftColor: "#7C3AED",
  },
  hwHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  daysLeft: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: "700",
  },
  scheduleSlideCard: {
    backgroundColor: "#1F2937",
    minHeight: 118,
    paddingVertical: 10,
    justifyContent: "center",
    gap: 6,
    borderLeftWidth: 4,
    borderLeftColor: "#38BDF8",
  },
  scheduleSlideCardToday: {
    backgroundColor: "#065F46",
    borderLeftColor: "#34D399",
  },
  scheduleSlideCardTomorrow: {
    borderLeftColor: "#38BDF8",
  },
  scheduleSlideCardCurrent: {
    backgroundColor: "#047857",
    height: 128,
    borderLeftWidth: 4,
    borderLeftColor: "#34D399",
    borderWidth: 2,
    borderColor: "#34D399",
    ...platformShadowAccent("#34D399"),
  },
  scheduleDayBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#334155",
    color: "#E2E8F0",
    fontSize: 11,
    fontWeight: "800",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 4,
    overflow: "hidden",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  scheduleDayBadgeToday: {
    backgroundColor: "#34D399",
    color: "#064E3B",
  },
  scheduleDayBadgeTomorrow: {
    backgroundColor: "#38BDF8",
    color: "#0C4A6E",
  },
  scheduleDateTime: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  scheduleDateTimeToday: { color: "#A7F3D0" },
  scheduleDateTimeTomorrow: { color: "#BAE6FD" },
  scheduleSubject: {
    color: "#F8FAFC",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  scheduleSubjectToday: { color: "#ECFDF5" },
  scheduleNoClassesCard: {
    backgroundColor: "#F1F5F9",
    height: 118,
    justifyContent: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#CBD5E1",
  },
  scheduleNoClassesTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 8,
  },
  scheduleNoClassesText: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  hwNoWorkCard: {
    backgroundColor: "#F8FAFC",
    height: isWeb ? undefined : 142,
    minHeight: isWeb ? 120 : undefined,
    justifyContent: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#CBD5E1",
  },
  examNoWorkCard: {
    backgroundColor: "#FAF5FF",
    height: isWeb ? undefined : 142,
    minHeight: isWeb ? 120 : undefined,
    justifyContent: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#C4B5FD",
  },
  hwNoWorkTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 8,
  },
  hwNoWorkText: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  slideCardFullWidth: isWeb
    ? ({ gridColumn: "1 / -1", maxWidth: "100%" } as ViewStyle)
    : {},
  feedBadge: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6B7280",
    textTransform: "uppercase",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  attendanceStatus: { fontSize: 14, fontWeight: "700", marginBottom: 2 },
  slideCardActionUrgent: { color: "#DC2626", fontWeight: "700" },
  alertButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  notificationBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: isWeb ? 0 : 2,
    borderColor: "#1E3A8A",
  },
  notificationBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  logoutText: {
    color: "#1E3A8A",
    fontWeight: "700",
    fontSize: 13,
  },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    padding: 24,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: { color: "#9CA3AF", fontWeight: "600", fontSize: 14 },
  absenceCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
  },
  absenceInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 14,
    minHeight: 88,
    marginBottom: 12,
    fontSize: 15,
  },
  absenceButton: {
    backgroundColor: "#2563EB",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  absenceButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 15 },
  scrollBottomSpacer: { height: isWeb ? 24 : 24 },
});

/** Mobile: original slideCard only. Web carousel: fixed-width slideCardInCarousel. */
export function studentSlideCardStyle(...extras: ViewStyle[]): ViewStyle[] {
  if (isWeb) {
    return [dashboardStyles.slideCard, dashboardStyles.slideCardInCarousel, ...extras];
  }
  return [dashboardStyles.slideCard, ...extras];
}
