import { StyleSheet } from "react-native";

export const teacherAttendanceStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  fixedHeader: {
    paddingHorizontal: 20,
    paddingBottom: 14,
    backgroundColor: "transparent",
  },
  scrollBody: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 120,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
  },
  sub: {
    marginTop: 12,
    fontSize: 16,
    fontWeight: "600",
    color: "#334155",
  },
  classRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
    marginBottom: 4,
  },
  classBtn: {
    padding: 10,
    backgroundColor: "#ddd",
    borderRadius: 10,
    margin: 5,
  },
  activeClass: { backgroundColor: "#3b82f6" },
  classText: { color: "#000" },
  activeClassText: { color: "#fff" },
  warning: { color: "#B91C1C", marginVertical: 10 },
  pickerTrigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 8,
  },
  pickerTriggerInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  pickerTriggerText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    flex: 1,
  },
  studentCount: {
    fontSize: 13,
    color: "#64748B",
    marginTop: 6,
    marginBottom: 12,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  navBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  navBtnText: { color: "#1E40AF", fontWeight: "600", fontSize: 14 },
  navCounter: { fontSize: 14, fontWeight: "600", color: "#64748B" },
  card: {
    backgroundColor: "white",
    padding: 18,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardName: { fontSize: 20, fontWeight: "800", marginBottom: 12, color: "#0F172A" },
  statusPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
  },
  statusPillText: { fontWeight: "700", fontSize: 14 },
  noMark: { fontSize: 14, color: "#94A3B8", marginBottom: 10 },
  parentReason: {
    fontSize: 14,
    color: "#166534",
    marginBottom: 10,
    lineHeight: 20,
  },
  waitingHint: {
    fontSize: 13,
    color: "#B91C1C",
    marginBottom: 12,
    fontStyle: "italic",
  },
  markRow: { gap: 10 },
  markBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
  },
  markPresent: { backgroundColor: "#16A34A" },
  markAbsent: { backgroundColor: "#DC2626" },
  markLate: { backgroundColor: "#D97706" },
  markBtnText: { color: "#FFFFFF", fontWeight: "700", fontSize: 16 },
  legend: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    marginTop: 8,
    marginBottom: 12,
    gap: 8,
  },
  legendRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  legendText: { flex: 1, fontSize: 13, color: "#475569" },
  sectionBox: {
    backgroundColor: "#FEF2F2",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  sectionBoxGreen: {
    backgroundColor: "#F0FDF4",
    borderColor: "#BBF7D0",
  },
  sectionTitle: { fontWeight: "700", fontSize: 15, color: "#0F172A" },
  sectionItem: {
    fontSize: 14,
    color: "#64748B",
    marginTop: 8,
    paddingVertical: 2,
  },
  recentCard: {
    width: 150,
    padding: 12,
    borderRadius: 12,
    marginRight: 10,
    borderWidth: 2,
  },
  recentDate: { fontSize: 12, color: "#64748B" },
  recentName: { fontWeight: "700", marginTop: 4, color: "#0F172A" },
  recentStatus: { fontWeight: "700", fontSize: 13, marginTop: 4 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.45)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "75%",
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  modalTitle: { fontSize: 18, fontWeight: "800", color: "#0F172A" },
  searchInput: {
    marginHorizontal: 20,
    marginBottom: 12,
    backgroundColor: "#F1F5F9",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  modalList: { paddingHorizontal: 20 },
  modalItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: "#F8FAFC",
  },
  modalItemActive: {
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#2563EB",
  },
  modalItemText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: "#334155",
    marginRight: 8,
  },
  modalItemTextActive: { color: "#1D4ED8" },
  modalItemBadge: { fontSize: 12, fontWeight: "700" },
  modalItemBadgeMuted: { fontSize: 12, color: "#94A3B8" },
  modalEmpty: {
    textAlign: "center",
    color: "#64748B",
    paddingVertical: 24,
  },
});
