import { StyleSheet } from "react-native";

export const teacherDashboardStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "transparent",
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  header: {
    backgroundColor: "#1E3A8A",
    paddingBottom: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingHorizontal: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  headerActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 12,
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  headerBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: "#1E3A8A",
  },
  headerBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "800",
  },
  logoutButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: "#1E3A8A",
    fontSize: 24,
    fontWeight: "700",
  },
  greeting: {
    color: "#DBEAFE",
    fontSize: 14,
  },
  teacherName: {
    color: "white",
    fontSize: 26,
    fontWeight: "700",
    marginTop: 4,
    lineHeight: 32,
  },
  actionsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  gradesBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    marginTop: 14,
    gap: 14,
    borderWidth: 1,
    borderColor: "#C4B5FD",
  },
  gradesBannerIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#F5F3FF",
    alignItems: "center",
    justifyContent: "center",
  },
  gradesBannerEmoji: { fontSize: 24 },
  gradesBannerText: { flex: 1 },
  gradesBannerTitle: {
    fontWeight: "700",
    fontSize: 15,
    color: "#5B21B6",
  },
  gradesBannerSub: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
    lineHeight: 16,
  },
  gradesBannerChevron: {
    fontSize: 28,
    color: "#94A3B8",
    fontWeight: "300",
  },
  absenceBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    marginTop: 14,
    gap: 14,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  absenceBannerIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  absenceBannerEmoji: { fontSize: 24 },
  absenceBannerText: { flex: 1 },
  absenceBannerTitle: {
    fontWeight: "700",
    fontSize: 15,
    color: "#1E3A8A",
  },
  absenceBannerSub: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
    lineHeight: 16,
  },
  absenceBannerChevron: {
    fontSize: 28,
    color: "#94A3B8",
    fontWeight: "300",
  },
  actionCard: {
    flex: 1,
    backgroundColor: "white",
    padding: 18,
    borderRadius: 18,
    alignItems: "center",
    position: "relative",
  },
  actionEmoji: {
    fontSize: 24,
    marginBottom: 10,
  },
  actionTitle: {
    fontWeight: "700",
    color: "#1F2937",
  },
  actionBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  actionBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  actionHint: {
    fontSize: 10,
    color: "#DC2626",
    fontWeight: "600",
    marginTop: 4,
  },
  statsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  statCard: {
    flex: 1,
    padding: 18,
    borderRadius: 18,
    alignItems: "center",
  },
  statValue: {
    fontSize: 28,
    fontWeight: "700",
    color: "#111827",
  },
  statLabel: {
    marginTop: 6,
    color: "#6B7280",
    fontWeight: "600",
  },
  section: {
    marginTop: 28,
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionHint: {
    marginTop: 4,
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  emptyHint: {
    fontSize: 14,
    color: "#94A3B8",
    paddingVertical: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  studentCard: {
    width: 148,
    backgroundColor: "white",
    borderRadius: 18,
    padding: 16,
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  studentAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#DBEAFE",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  studentAvatarText: {
    color: "#1D4ED8",
    fontWeight: "700",
    fontSize: 20,
  },
  studentName: {
    fontWeight: "700",
    color: "#111827",
    fontSize: 15,
    textAlign: "center",
    marginTop: 4,
  },
  studentReportHint: {
    fontSize: 11,
    color: "#7C3AED",
    fontWeight: "700",
    marginTop: 8,
    textAlign: "center",
  },
  announcementCard: {
    width: 280,
    backgroundColor: "white",
    padding: 18,
    borderRadius: 18,
    marginRight: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#2563EB",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
    color: "#111827",
  },
  cardText: {
    color: "#6B7280",
    lineHeight: 20,
  },
  scrollBottomSpacer: { height: 120 },
});
