import { Platform, StyleSheet, type ViewStyle } from "react-native";
import {
  INNER_CARD_BORDER_GREEN,
  INNER_CARD_BORDER_RED,
} from "../../src/constants/innerCardBorders";

const isWeb = Platform.OS === "web";

const webActionGrid: ViewStyle = isWeb
  ? {
      display: "grid",
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
      gap: 12,
    }
  : {};

export const teacherDashboardStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "transparent",
  },
  container: {
    flex: 1,
    paddingHorizontal: isWeb ? 0 : 16,
  },
  scrollContent: {
    paddingBottom: isWeb ? 32 : 120,
  },
  headerSafe: {
    backgroundColor: "#1E3A8A",
  },
  header: {
    backgroundColor: "#1E3A8A",
    paddingTop: isWeb ? 12 : 0,
    paddingBottom: isWeb ? 18 : 20,
    borderBottomLeftRadius: isWeb ? 0 : 28,
    borderBottomRightRadius: isWeb ? 0 : 28,
    paddingHorizontal: isWeb ? 0 : 16,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: isWeb ? 0.08 : 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  headerInner: {
    width: "100%",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: isWeb ? 12 : 14,
    minHeight: isWeb ? 72 : undefined,
  },
  headerTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  headerIconButtonNative: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  headerBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: isWeb ? 0 : 1.5,
    borderColor: "#1E3A8A",
  },
  headerBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "800",
  },
  greeting: {
    color: "#BFDBFE",
    fontSize: 13,
    fontWeight: "500",
  },
  teacherName: {
    color: "#FFFFFF",
    fontSize: isWeb ? 20 : 26,
    fontWeight: "800",
    marginTop: 2,
    lineHeight: isWeb ? 26 : 32,
  },
  actionsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: isWeb ? 4 : 20,
    ...webActionGrid,
  },
  linkBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: isWeb ? 10 : 18,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: INNER_CARD_BORDER_RED,
    width: "100%",
    marginTop: isWeb ? 12 : 14,
    position: "relative",
  },
  linkBannerIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  linkBannerText: { flex: 1, minWidth: 0 },
  linkBannerTitle: {
    fontWeight: "700",
    fontSize: 15,
    color: "#0F172A",
  },
  linkBannerSub: {
    fontSize: 13,
    color: "#64748B",
    marginTop: 4,
    lineHeight: 18,
  },
  actionCard: {
    flex: isWeb ? undefined : 1,
    backgroundColor: "#FFFFFF",
    padding: isWeb ? 16 : 18,
    borderRadius: isWeb ? 10 : 18,
    alignItems: "center",
    position: "relative",
    borderWidth: 1,
    borderColor: INNER_CARD_BORDER_GREEN,
    minHeight: isWeb ? 108 : undefined,
    justifyContent: "center",
  },
  actionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  actionTitle: {
    fontWeight: "700",
    color: "#0F172A",
    fontSize: 14,
    textAlign: "center",
  },
  actionBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  actionBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  actionHint: {
    fontSize: 11,
    color: "#DC2626",
    fontWeight: "600",
    marginTop: 6,
    textAlign: "center",
  },
  statsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: isWeb ? 0 : 20,
  },
  statCard: {
    flex: 1,
    padding: 18,
    borderRadius: isWeb ? 10 : 18,
    alignItems: "center",
    borderWidth: isWeb ? 1 : 0,
    borderColor: INNER_CARD_BORDER_GREEN,
  },
  statValue: {
    fontSize: 28,
    fontWeight: "800",
    color: "#0F172A",
  },
  statLabel: {
    marginTop: 6,
    color: "#64748B",
    fontWeight: "600",
    fontSize: 14,
  },
  section: {
    marginTop: isWeb ? 12 : 28,
    ...(isWeb
      ? {
          backgroundColor: "#FFFFFF",
          borderRadius: 12,
          padding: 16,
          borderWidth: 1,
          borderColor: INNER_CARD_BORDER_RED,
        }
      : null),
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionHint: {
    marginTop: 4,
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  emptyHint: {
    fontSize: 14,
    color: "#94A3B8",
    paddingVertical: 12,
  },
  sectionTitle: {
    fontSize: isWeb ? 15 : 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  studentSearchInput: {
    backgroundColor: "#F1F5F9",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: INNER_CARD_BORDER_GREEN,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    marginBottom: 12,
  },
  studentListPagination: {
    marginBottom: 12,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: INNER_CARD_BORDER_GREEN,
  },
  studentCard: {
    width: isWeb ? undefined : 148,
    minWidth: isWeb ? 140 : undefined,
    flexGrow: isWeb ? 1 : undefined,
    flexBasis: isWeb ? ("31%" as const) : undefined,
    backgroundColor: "#FFFFFF",
    borderRadius: isWeb ? 10 : 18,
    padding: 16,
    alignItems: "center",
    marginRight: isWeb ? 0 : 12,
    marginBottom: isWeb ? 0 : 8,
    borderWidth: 1,
    borderColor: INNER_CARD_BORDER_GREEN,
  },
  studentName: {
    fontWeight: "700",
    color: "#0F172A",
    fontSize: 15,
    textAlign: "center",
    marginTop: 4,
  },
  studentReportHint: {
    fontSize: 11,
    color: "#7C3AED",
    fontWeight: "700",
    marginTop: 8,
    textAlign: "center",
  },
  announcementCard: {
    width: 260,
    height: 142,
    marginRight: 12,
    flexShrink: 0,
    backgroundColor: "#FFFFFF",
    padding: 14,
    borderRadius: isWeb ? 10 : 16,
    borderLeftWidth: 4,
    borderLeftColor: INNER_CARD_BORDER_RED,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: INNER_CARD_BORDER_GREEN,
    borderRightColor: INNER_CARD_BORDER_GREEN,
    borderBottomColor: INNER_CARD_BORDER_GREEN,
    justifyContent: "space-between",
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
    color: "#0F172A",
  },
  cardText: {
    flex: 1,
    color: "#64748B",
    lineHeight: 18,
    fontSize: 13,
  },
  cardReadMore: {
    marginTop: 8,
    color: "#2563EB",
    fontWeight: "700",
    fontSize: 12,
  },
  detailLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
  },
  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: INNER_CARD_BORDER_RED,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
  },
  detailBody: {
    fontSize: 16,
    lineHeight: 24,
    color: "#334155",
  },
  detailDeleteBtn: {
    marginTop: 16,
    backgroundColor: "#DC2626",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
  },
  detailDeleteBtnDisabled: {
    opacity: 0.7,
  },
  detailDeleteBtnText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
  },
  scrollBottomSpacer: { height: isWeb ? 24 : 120 },
});
