import { Platform, StyleSheet } from "react-native";
import { WEB_PAGE_MAX_WIDTH_DESKTOP } from "../../hooks/usePlatformLayout";

const isWeb = Platform.OS === "web";

export const WEB_LANDING_MAX_WIDTH = WEB_PAGE_MAX_WIDTH_DESKTOP;

const webOnly = (style: object) => (isWeb ? style : {});

export const LANDING_GRADIENT_CARD_WEB = {
  backgroundImage:
    "linear-gradient(125deg, #DDD6FE 0%, #C4B5FD 18%, #93C5FD 42%, #BFDBFE 58%, #FDE68A 92%)",
  boxShadow:
    "0 24px 60px rgba(99, 102, 241, 0.16), 0 8px 24px rgba(15, 23, 42, 0.06)",
};

export const webLandingStyles = StyleSheet.create({
  root: {
    flex: 1,
    width: "100%",
    backgroundColor: "#FAFAFA",
    minHeight: isWeb ? ("100vh" as unknown as number) : undefined,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 48,
  },
  page: {
    width: "100%",
    maxWidth: WEB_LANDING_MAX_WIDTH,
    alignSelf: "center",
    paddingHorizontal: isWeb ? 40 : 20,
  },
  utilityBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    gap: 12,
    flexWrap: "wrap",
  },
  utilityLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  utilityRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 16,
    flexWrap: "wrap",
    flexShrink: 1,
    minWidth: 0,
  },
  utilityTagline: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 1,
    textAlign: "right",
  },
  utilityLink: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "600",
  },
  navbar: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: isWeb ? 18 : 14,
    gap: isWeb ? 20 : 12,
    flexWrap: isWeb ? "nowrap" : "wrap",
    ...webOnly({
      position: "sticky",
      top: 0,
      zIndex: 20,
      backgroundColor: "rgba(250, 250, 250, 0.92)",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      display: "grid",
      gridTemplateColumns: "auto minmax(0, 1fr) auto",
      columnGap: 20,
    }),
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 0,
    ...webOnly({
      gridColumn: 1,
      gridRow: 1,
    }),
  },
  brandTextWrap: {
    minWidth: 0,
  },
  brandName: {
    fontSize: isWeb ? 20 : 18,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -0.3,
  },
  brandTag: {
    fontSize: 12,
    fontWeight: "500",
    color: "#94A3B8",
    marginTop: 1,
  },
  navLinks: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: isWeb ? 20 : 16,
    flexWrap: isWeb ? "nowrap" : "wrap",
    flex: isWeb ? undefined : 1,
    minWidth: 0,
    ...webOnly({
      gridColumn: 2,
      gridRow: 1,
      justifySelf: "center",
    }),
  },
  navLinkBtn: {
    paddingVertical: 4,
    paddingHorizontal: 2,
    flexShrink: 0,
  },
  navLink: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "600",
    ...webOnly({
      whiteSpace: "nowrap",
    }),
  },
  navCta: {
    backgroundColor: "#0F172A",
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 999,
    flexShrink: 0,
    ...webOnly({
      boxShadow: "0 4px 14px rgba(15, 23, 42, 0.18)",
      gridColumn: 3,
      gridRow: 1,
      justifySelf: "end",
    }),
  },
  navCtaText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
  },
  heroCard: {
    marginTop: isWeb ? 12 : 8,
    marginBottom: isWeb ? 48 : 32,
    borderRadius: isWeb ? 28 : 22,
    overflow: "hidden",
    padding: isWeb ? 48 : 24,
    ...webOnly(LANDING_GRADIENT_CARD_WEB),
  },
  heroRow: {
    flexDirection: isWeb ? "row" : "column",
    alignItems: isWeb ? "center" : "stretch",
    gap: isWeb ? 40 : 28,
  },
  heroCopy: {
    flex: isWeb ? 1.05 : undefined,
    minWidth: 0,
    gap: 18,
  },
  heroMedia: {
    flex: isWeb ? 0.95 : undefined,
    width: isWeb ? undefined : "100%",
    minWidth: 0,
    alignItems: "center",
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.22)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  heroBadgeText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.4,
  },
  heroTitle: {
    fontSize: isWeb ? 46 : 32,
    fontWeight: "800",
    color: "#FFFFFF",
    lineHeight: isWeb ? 54 : 38,
    letterSpacing: isWeb ? -1.2 : -0.6,
    maxWidth: 560,
  },
  heroHighlight: {
    color: "#FFFFFF",
    opacity: 0.92,
  },
  heroSubtitle: {
    fontSize: isWeb ? 17 : 15,
    lineHeight: isWeb ? 28 : 24,
    color: "rgba(255,255,255,0.88)",
    maxWidth: 520,
  },
  heroActions: {
    flexDirection: isWeb ? "row" : "column",
    alignItems: isWeb ? "center" : "stretch",
    gap: 12,
    marginTop: 4,
  },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#0F172A",
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 999,
    minWidth: isWeb ? 190 : undefined,
    ...webOnly({
      boxShadow: "0 8px 24px rgba(15, 23, 42, 0.22)",
    }),
  },
  primaryBtnText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
  },
  secondaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    minWidth: isWeb ? 190 : undefined,
  },
  secondaryBtnText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
  },
  heroVideoWrap: {
    width: "100%",
    maxWidth: isWeb ? 520 : 400,
    aspectRatio: 16 / 9,
    borderRadius: 18,
    overflow: "hidden",
    alignSelf: "center",
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.55)",
    backgroundColor: "#0F172A",
    ...(isWeb
      ? ({
          maxHeight: 292,
          boxShadow: "0 20px 40px rgba(15, 23, 42, 0.24)",
        } as object)
      : null),
  },
  heroRating: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  heroRatingText: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 13,
    fontWeight: "700",
  },
  trustSection: {
    alignItems: "center",
    paddingVertical: isWeb ? 28 : 20,
    marginBottom: isWeb ? 16 : 8,
    gap: 18,
  },
  trustLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#94A3B8",
    textAlign: "center",
    letterSpacing: 0.2,
  },
  trustRoles: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    maxWidth: 900,
  },
  trustRole: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    ...webOnly({
      boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    }),
  },
  trustRoleText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#475569",
  },
  featuresSection: {
    paddingBottom: 8,
    ...webOnly({
      scrollMarginTop: 96,
    }),
  },
  featuresCard: {
    borderRadius: isWeb ? 28 : 22,
    overflow: "hidden",
    padding: isWeb ? 48 : 28,
    ...webOnly(LANDING_GRADIENT_CARD_WEB),
  },
  sectionEyebrow: {
    fontSize: 13,
    fontWeight: "700",
    color: "rgba(255,255,255,0.85)",
    textTransform: "uppercase",
    letterSpacing: 1,
    textAlign: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: isWeb ? 38 : 28,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
    lineHeight: isWeb ? 46 : 34,
    letterSpacing: isWeb ? -0.8 : -0.4,
    maxWidth: 760,
    alignSelf: "center",
  },
  sectionHint: {
    fontSize: isWeb ? 17 : 15,
    color: "rgba(255,255,255,0.88)",
    textAlign: "center",
    marginTop: 16,
    marginBottom: isWeb ? 28 : 20,
    lineHeight: isWeb ? 28 : 24,
    maxWidth: 640,
    alignSelf: "center",
  },
  capabilityRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    marginBottom: isWeb ? 32 : 24,
    maxWidth: 820,
    alignSelf: "center",
  },
  capabilityPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.7)",
    ...webOnly({
      boxShadow: "0 2px 10px rgba(15, 23, 42, 0.06)",
    }),
  },
  capabilityText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
  },
  featureGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 18,
    justifyContent: "center",
  },
  featureCard: {
    width: isWeb ? "47%" : "100%",
    maxWidth: 540,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 20,
    padding: isWeb ? 24 : 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    ...webOnly({
      boxShadow: "0 8px 30px rgba(15, 23, 42, 0.08)",
    }),
  },
  featureIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 8,
  },
  featureBody: {
    fontSize: 14,
    lineHeight: 22,
    color: "#64748B",
  },
  footer: {
    marginTop: isWeb ? 64 : 40,
    paddingTop: 28,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    alignItems: "center",
    gap: 16,
  },
  footerLinks: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 20,
  },
  footerLink: {
    color: "#334155",
    fontWeight: "600",
    fontSize: 14,
  },
  footerCopy: {
    color: "#94A3B8",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
  },
});
